### ISSUE TITLE
Status : Connected but no torrent displayed

### ISSUE THREAD

**Issue by Galixte** [Feverqwe/Transmission#2]
Hello there, 
and thank you for this extension. 
I do not see the download in progress or completed, after installing the extension on Opera v27.1689.54. 

I have always an error : "not found (code 404)"

My configuration :

Transmission vTransmission 2.84 (14307)
IP : xx.xx.xx.xx
Port : 9091
Path : web/#files

If i click on button "Plugin WebUI", everything it's OK.

I don't understand.

**Comment by Galixte** [comment]
Hi,

six months later, i have always an error : "not found (code 404)"

Same configuration :

Transmission vTransmission 2.84 (14307)
IP : xx.xx.xx.xx
Port : 9091
Path : web/#files

If i click on button "Plugin WebUI", everything it's OK.

I don't understand.

**Comment by Feverqwe** [comment]
Hello!
In settings you can change webUI path and RPC path.
404 error talk about bad RPC path.

2015-01-30 7:37 GMT+05:00 Raphaël <notifications@github.com>:

**Comment by Galixte** [comment]
Finally i found !

It solve 404, 405 and 409 errors.

Transmission version : 2.84 (14307)
IP : xx.xx.xx.xx
Port : 9091
WebUI Path : web/#files
RPC Path : rpc/

Thanks ;=)
