### ISSUE TITLE
Mozilla Firefox 61.0 : no prompt when adding a new torrent

### ISSUE THREAD

**Issue by JSchoreels** [Feverqwe/Transmission#5]
When right clicking on a torrent -> "Add" in firefox 61, I don't have any prompting to add the torrent in a directory.

After some elementary debugging, it happens here : 

>  onCtxMenuCall: function (a) {
>     ....
>     if ('newFolder' === d) {
>       var g = prompt(engine.language.enterNewDirPath, e[1]);

I don't really know what the problem is, but here is the error in console :

> 
> NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindowUtils.isParentWindowMainWidgetVisible] nsPrompter.js:339
> DebuggeeWouldRun: debuggee `moz-extension://b54e56d9-d04e-405d-b607-70277fd98443/js/background.js:13' would run event-loop.js:118:5
> Attempt to set a forbidden header was denied: Connection 489779108-lcs_client_bin.js:193:386
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=ACT-Web-JS-2.9.0&x-apikey=c6c190a1b73c4a63bba89835d546cf28-f2a0482f-a00d-48d9-822e-e89cc89eb64d-7688. (Reason: CORS request did not succeed).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=ACT-Web-JS-2.9.0&x-apikey=c6c190a1b73c4a63bba89835d546cf28-f2a0482f-a00d-48d9-822e-e89cc89eb64d-7688. (Reason: CORS request did not succeed).
> [Show/hide message details.] [Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: moz-extension://b54e56d9-d04e-405d-b607-70277fd98443/js/background.js :: onCtxMenuCall :: line 30"  data: no]
> onCtxMenuCall
> background.js:formatted:753
> dispatchEvent
> chrome://browser/content/child/ext-menus.js:35:7
> dispatchEvent self-hosted:986:17 apply self-hosted:4613:5 applySafeWithoutClone
> resource://gre/modules/ExtensionCommon.jsm:234:16
> fire
> resource://gre/modules/ExtensionChild.jsm:897:28
> receiveMessage
> resource://gre/modules/ExtensionChild.jsm:900:38
> _callHandlers/<
> resource://gre/modules/MessageChannel.jsm:866:17
> _callHandlers
> resource://gre/modules/MessageChannel.jsm:865:14
> _handleMessage/deferred.promise<
> resource://gre/modules/MessageChannel.jsm:940:7
> _handleMessage
> resource://gre/modules/MessageChannel.jsm:937:24
> _handleMessage self-hosted:986:17 receiveMessage/<
> resource://gre/modules/MessageChannel.jsm:208:9
> forEach self-hosted:268:13 receiveMessage
> resource://gre/modules/MessageChannel.jsm:201:5
>

**Comment by Feverqwe** [comment]
Fixed
